### ISSUE TITLE
生产环境发送推送后无反应

### ISSUE THREAD

**Issue by wulinman** [shaojiankui/SmartPush#23]
1. 点击推送后，发送推送，但没有收到回包的感觉
2. 手机没有收到推送
![image](https://user-images.githubusercontent.com/22051088/133543997-53e526e3-5b9f-4ef2-8ece-5360aaf3837f.png)

**Comment by wulinman** [comment]
log：unregister notification for read_timeout failed
![image](https://user-images.githubusercontent.com/22051088/133544894-51042991-7200-4bc1-a3c0-351706bb0e2b.png)

**Comment by shaojiankui** [comment]
已解决 topic_name获取问题
