### ISSUE TITLE
拖动文件，topicName为空，会报MissingTopic的错误

### ISSUE THREAD

**Issue by bbaiqiang** [shaojiankui/SmartPush#24]
手动导入证书进去，即证书名称后面带 文件时，
该证书的topicName为空，会报MissingTopic的错误

**Comment by xiaochuan4938** [comment]
hi， 请问怎么解决？

**Comment by YanBoCode** [comment]
你那边 也报这个错误吗？解决了没有  我这边也是 一直这个错误  MissingTopic  MissingTopic   MissingTopic

**Comment by bbaiqiang** [comment]
> 不要通过证书路径(拖拽也是)导入证书。双击证书，装到keychain里，再选择证书就可以(SmartPush会遍历keychain里的可用证书)

**Comment by YanBoCode** [comment]
这个时候我需要怎么操作，把证书删掉重新弄吗？还是怎么弄

发自我的iPhone

**Comment by YanBoCode** [comment]
重启一下  就好了，选择的证书  现在提示 发送成功了  但是 手机 没有 收到推送 ，尴尬

**Comment by YanBoCode** [comment]
现在测试环境推送 是OK的  可以的，但是生成环境报  BadDeviceToken 这个错误，你遇到过没有，我打的 推送证书，就是开发环境和正式环境都可以的。

**Comment by YanBoCode** [comment]
现在测试环境推送 是OK的 可以的，但是生成环境报 BadDeviceToken 这个错误，你遇到过没有，我打的 推送证书，就是开发环境和正式环境都可以的。

**Comment by bbaiqiang** [comment]
检查DeviceToken是否正确，检查证书配置是否正确，两个环境下的DeviceToken不应该相同。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shaojiankui/SmartPush"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 下午2:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shaojiankui/SmartPush] 拖动文件，topicName为空，会报MissingTopic的错误 (Issue #24)





 
现在测试环境推送 是OK的 可以的，但是生成环境报 BadDeviceToken 这个错误，你遇到过没有，我打的 推送证书，就是开发环境和正式环境都可以的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YanBoCode** [comment]
> 检查DeviceToken是否正确，检查证书配置是否正确，两个环境下的DeviceToken不应该相同。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "shaojiankui/SmartPush" ***@***.***&gt;; 发送时间:&nbsp;2022年2月15日(星期二) 下午2:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [shaojiankui/SmartPush] 拖动文件，topicName为空，会报MissingTopic的错误 (Issue #24) 现在测试环境推送 是OK的 可以的，但是生成环境报 BadDeviceToken 这个错误，你遇到过没有，我打的 推送证书，就是开发环境和正式环境都可以的。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

解决了  多谢  多谢

**Comment by bbaiqiang** [comment]
不客气




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 下午3:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shaojiankui/SmartPush] 拖动文件，topicName为空，会报MissingTopic的错误 (Issue #24)





  
检查DeviceToken是否正确，检查证书配置是否正确，两个环境下的DeviceToken不应该相同。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "shaojiankui/SmartPush" @.&gt;; 发送时间:&nbsp;2022年2月15日(星期二) 下午2:00 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [shaojiankui/SmartPush] 拖动文件，topicName为空，会报MissingTopic的错误 (Issue #24) 现在测试环境推送 是OK的 可以的，但是生成环境报 BadDeviceToken 这个错误，你遇到过没有，我打的 推送证书，就是开发环境和正式环境都可以的。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
解决了  多谢  多谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaojiankui** [comment]
已经解决，之前从文件直接选择的证书 没有自动获取topicName
