### ISSUE TITLE
MissingTopic

### ISSUE THREAD

**Issue by YanBoCode** [shaojiankui/SmartPush#25]
不知道为什么 一直 报这个错误 ，有人遇到过没有
MissingTopic

**Comment by hrlr1230** [comment]
具体逻辑在PushViewController.mm里，没仔细看 , _currentSec打印了是空
“ withTopic:_currentSec?_currentSec.topicName:@"" ”，直接替换你的topic，先用着就行
如：withTopic:@"com.xxx.yyy"

**Comment by shaojiankui** [comment]
已经解决，之前从文件直接选择的证书 没有自动获取topicName
