### ISSUE TITLE
Apple Sandbox Push Services类型证书问题

### ISSUE THREAD

**Issue by roger-int** [shaojiankui/SmartPush#28]
选择Apple Sandbox Push Services类型的证书，提示"不是有效的推送证书"？
<img width="260" alt="image" src="https://user-images.githubusercontent.com/13251150/155253632-b85d4d10-f6b6-475b-84ae-2d98df703de1.png">

**Comment by hrlr1230** [comment]
看推送请求那里，有人提了解决方案，
SecManager.mm文件 isPushCertificate方法下，加多行判断
“|| [name rangeOfString:@"Apple Sandbox Push Services:"].location != NSNotFound”即可
