### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by Z-Seven** [shaojiankui/SmartPush#3]
添加证书后无法连接到服务器，用的是开发的apns证书，连接到开发环境，错误是：
SSL端点域名不能被设置 -25300
Keychain中不能找到证书 -25300
SSL证书不能被设置 -50

**Comment by shaojiankui** [comment]
证书要安装到keychain中

**Comment by tennysondy** [comment]
我也遇到这个问题了，证书装到keychain里还是不行啊

**Comment by fengxuelei** [comment]
相同的问题是你们找到原因没？

**Comment by zilaiyedaren** [comment]
我这边也遇到了同样的问题，证书已经放置到keychain中

**Comment by zilaiyedaren** [comment]
SSL端点域名不能被设置 -25300
Keychain中不能找到证书 -25300
SSL证书不能被设置 -50

**Comment by YanxiFeng** [comment]
我也是这样的问题。

**Comment by 492789706** [comment]
SSL握手证书过期 -9828

**Comment by htxian** [comment]
证书要包含私钥的才可以。

**Comment by lanmoyingsheng** [comment]
需要p12文件，其他开发者导出的包含密钥的p12文件。
