### ISSUE TITLE
macOS10.12.6上不支持storyboard

### ISSUE THREAD

**Issue by ClayGuitar** [shaojiankui/SmartPush#5]
。。。

**Comment by shaojiankui** [comment]
fixed

**Comment by bestK** [comment]
10.13.6 (17G65) 

Storyboards are not available before macOS 10.10 [12]

**Comment by guolimk** [comment]
> fixed

请问一下，您是如何解决的？

**Comment by kgart213** [comment]
> > fixed
> 
> 请问一下，您是如何解决的？

打开storyboard，选中视图， 有一个build for选项，你选择10.10以后就行了，默认10.8 ，所以报那个错误了
